apiVersion: v1
kind: Service
metadata:
  name: {{ include "flux-web.fullname" . }}-backend
  labels:
{{ include "flux-web.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "flux-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
